services:

  fail2ban:
    image: crazymax/fail2ban:latest
    container_name: fail2ban
    network_mode: "host"
    cap_add:
      - NET_ADMIN
      - NET_RAW
    volumes:
      - ./data/:/data/
      - /var/log:/var/log:ro
#      - ./root/docker/proxy-manager/data/logs:/log/npm/:ro      
    env_file:
      - ./fail2ban.env
    restart: unless-stopped
